version: '3.8'

services:
  #container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    command: -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global

  #server metrics
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      mode: global
    networks:
      - reverse-proxy
      - default
      
networks:
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  default: